import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import InputArea from "@/components/InputAreanputArea";


export default function Home() {

  const[input,setInput] = useState();


  const classFilters = {
    1: 'Magician',
    2: 'Theif',
    4: 'Warrior',
    8: 'Bowman',
    16: 'Pirate',
    32: 'Nothing'
  }

const getClassStyle = flagValue => (input & flagValue) > 0 ? { backgroundColor: 'yellow'} : null; 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div class="dataArea">
          <InputArea/>
          <div class="posterArea" >                                                             need to change to posters
            <table> 
              <tbody>
                {
                  Object.keys(classFilters).map(item => (
                    <tr key={item} style={getClassStyle(item)}>
                      <td>{item}</td> 
                      <td>{classFilters[item]}</td>
                    </tr>
                  ))
                }
              </tbody>
            </table>
          </div>
        </div>
      </main>
      <footer>
        Footer Area
      </footer>
    </>
  );
}